

// const jokes = [
//     "Why don't scientists trust atoms? Because they make up everything!",
//     "Parallel lines have so much in common. It's a shame they'll never meet.",
//     "I used to play piano by ear, but now I use my hands.",
//     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
//     "I'm reading a book on anti-gravity. It's impossible to put down!",
//     "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
//     "I'm on a seafood diet. I see food and I eat it.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why did the scarecrow win an award? Because he was outstanding in his field.",
//     "Why was the math book sad? Because it had too many problems.",
//     "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
//     "I'm friends with all electricians. We have such good current connections.",
//     "Why did the tomato turn red? Because it saw the salad dressing.",
//     "What do you call a fish with no eyes? Fsh.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why can't you give Elsa a balloon? Because she will let it go.",
//     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
//     "Why did the scarecrow win an award? Because he was outstanding in his field.",
//     "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
//     "Why don't skeletons fight each other? They don't have the guts.",
//     "What's orange and sounds like a parrot? A carrot.",
//     "I'm friends with all electricians. We have such good current connections.",
//     "Why was the math book sad? Because it had too many problems.",
//     "How do you organize a space party? You 'planet.'",
//     "Why did the tomato turn red? Because it saw the salad dressing.",
//     "What do you call a fish with no eyes? Fsh.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why can't you give Elsa a balloon? Because she will let it go.",
//     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
//     "Why did the scarecrow win an award? Because he was outstanding in his field.",
//     "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
//     "Why don't skeletons fight each other? They don't have the guts.",
//     "What's orange and sounds like a parrot? A carrot.",
//     "I'm friends with all electricians. We have such good current connections.",
//     "Why was the math book sad? Because it had too many problems.",
//     "How do you organize a space party? You 'planet.'",
//     "Why did the tomato turn red? Because it saw the salad dressing.",
//     "What do you call a fish with no eyes? Fsh.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why can't you give Elsa a balloon? Because she will let it go.",
//     "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
//     "Why don't skeletons fight each other? They don't have the guts.",
//     "What's orange and sounds like a parrot? A carrot.",
//     "I'm friends with all electricians. We have such good current connections.",
//     "Why was the math book sad? Because it had too many problems.",
//     "How do you organize a space party? You 'planet.'",
//     "Why did the tomato turn red? Because it saw the salad dressing.",
//     "What do you call a fish with no eyes? Fsh.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why can't you give Elsa a balloon? Because she will let it go.",
//     "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
//     "Why don't skeletons fight each other? They don't have the guts.",
//     "What's orange and sounds like a parrot? A carrot.",
//     "I'm friends with all electricians. We have such good current connections.",
//     "Why was the math book sad? Because it had too many problems.",
//     "How do you organize a space party? You 'planet.'",
//     "Why did the tomato turn red? Because it saw the salad dressing.",
//     "What do you call a fish with no eyes? Fsh.",
//     "I used to be a baker, but I couldn't make enough dough.",
//     "Why can't you give Elsa a balloon? Because she will let it go.",
//     "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
//     "Why don't skeletons"
//   ];
const jokes = [
    "Every day is a new beginning.",
    "Your smile can change the world.",
    "You are stronger than you think.",
    "Believe in yourself; you've got this!",
    "Chase your dreams relentlessly.",
    "Keep your face always toward the sunshine.",
    "Spread kindness like confetti.",
    "Find joy in the little things.",
    "Love and laughter are priceless.",
    "Embrace the journey; it's beautiful.",
    "You're a rainbow in someone's cloud.",
    "Life is a gift; treasure every moment.",
    "Dream big and fear less.",
    "The best is yet to come.",
    "You are enough, just as you are.",
    "Positive vibes only.",
    "Live, love, and laugh.",
    "Your potential is limitless.",
    "Success starts with a smile.",
    "Life is a beautiful adventure.",
    "Happiness is a choice.",
    "Be the reason someone smiles today.",
    "Find beauty in everyday moments.",
    "You are a star; shine on!",
    "Kindness is free; sprinkle that stuff everywhere.",
    "Dance through life's storms.",
    "Believe in miracles.",
    "Radiate positivity.",
    "Your happiness matters.",
    "Today is full of possibilities.",
    "Stay awesome!",
    "Love yourself first.",
    "Live with no regrets.",
    "Make each day your masterpiece.",
    "Adventure awaits!",
    "Be the light in the darkness.",
    "Life is better with a smile.",
    "Follow your heart.",
    "You are unique and amazing.",
    "Stay positive, work hard, make it happen.",
    "Be a voice, not an echo.",
    "Choose joy.",
    "You are loved more than you know.",
    "You're a diamond; they can't break you.",
    "Life is what you make it.",
    "Inhale courage, exhale fear.",
    "You've got the power.",
    "Find your happy place.",
    "Keep calm and carry on.",
    "Live in the moment.",
    "Smiles are contagious.",
    "Chase your dreams with determination.",
    "Make your own sunshine.",
    "You are a work of art.",
    "Choose to be optimistic.",
    "Be kind to yourself.",
    "Love and be loved.",
    "Dreams do come true.",
    "Your heart knows the way.",
    "Life is beautiful; cherish it.",
    "You are a masterpiece.",
    "Good things take time.",
    "You are worthy of happiness.",
    "Keep your head up.",
    "Live a life you love.",
    "Stay true to yourself.",
    "Shine bright like a star.",
    "Laughter is the best medicine.",
    "Believe in the magic of new beginnings.",
    "Seize the day.",
    "Your smile is your superpower.",
    "Stay positive; stay fighting.",
    "You are braver than you believe.",
    "Love conquers all.",
    "You are the architect of your destiny.",
    "Create your own sunshine.",
    "The future is bright.",
    "Keep moving forward.",
    "You are a source of inspiration.",
    "Live life to the fullest.",
    "You are amazing, just as you are.",
    "Stay focused and never give up.",
    "Believe in the beauty of your dreams.",
    "Dance to the beat of your heart.",
    "Life is an incredible journey.",
    "Embrace the adventure.",
    "Let your light shine.",
    "You've got the keys to success.",
    "Live with passion.",
    "Your potential is endless.",
    "Change the world with your smile.",
    "Every day is a blessing.",
    "Happiness is found within.",
    "You are the author of your story.",
    "You are a spark of joy.",
    "Dream big, work hard.",
    "Your strength is your smile.",
    "Keep calm and smile on.",
    "You've got this!",
    "Life is beautiful; celebrate it."
  ];
  
 
  

  let random=Math.floor(Math.random()*jokes.length);
  joke.innerHTML=jokes[random];


  


